codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "100...100"

  status:
    project:
      default:
        enabled: true
        target: 100%
    patch: false
    changes: false

comment: false