name: Styles

on: [push, pull_request]

jobs:
  lint:
    name: Lint code

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install poetry
        run: pip install poetry==1.1

      - uses: actions/cache@v2.1.6
        id: cache-dev-deps
        with:
          path: .venv
          key: venv-dev-${{ runner.os }}-py-3.9-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            venv-dev-${{ runner.os }}-py-3.9-poetry-
            venv-dev-${{ runner.os }}-py-3.9-
            venv-dev-${{ runner.os }}-py-
            venv-dev-${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-dev-deps.outputs.cache-hit != 'true'
        run: |
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run linters
        run: poetry run ./scripts/lint
